### ISSUE TITLE
Using r2dbc-client with RS implementation besides Reactor

### ISSUE THREAD

**Issue by aguibert** [r2dbc/r2dbc-client#30]
Currently the r2dbc-spi project only requires org.reactive-streams at the API level, and a DB vendor may implement the SPI using any RS implementation they choose.

However, r2dbc-client defines a hard dependency on reactor-core.  This is unfortunate because r2dbc-client itself is a pretty lightweight wrapper around the SPI.  All of the leg-work seems to be done by the SPI implementation.  If I was using an SPI implementation where the DB vendor implementation chose Akka Streams or RxJava as their RS implementation, it would be nice to not have to pull in Reactor Core (a 1.5MB dependency) to do the client-level wrapper logic.

It would probably be overkill to put r2dbc-client APIs behind RS-impl agnostic interfaces, so I was wondering if the R2DBC folks would be open to the idea of alternative r2dbc client libraries that used different RS impls, such as `r2dbc-client-rxjava` or `r2dbc-client-akka` under the r2dbc org?

**Comment by smaldini** [comment]
I think some of the concepts port naturally well to rxjava, reactor being a slightly lighter version of it with 2 super type out of 5. I don't think the size of the single jar is too much of a problem if the encapsulation is ok (reactor-core package private mostly 75% of its code exposing public api when really required). 

One requirement tho that might compete with akka api design is the concept of 0-1 Publisher type Mono when Akka Stream might chose to rely on CompletionStage. We wouldn't express the R2DBC API with Iterable<T> everywhere if it was blocking, so it makes sense to at least have these 2 different Publisher types Flux and Mono. RxJava Completable/Single/Maybe don't implement Publisher neither so that might be a problem (I think rxjava 3 will correct course there).

Finally one thing that might be useful to rely on downstream for implementors is the reactor-core execution Context, which might have an alternative with Akka but not with RxJava. As a relational database access we expect to port some non functional requirements such as transactional support, metrics, tracing and possibly security via the Context. We sure could do without it and have another contract for hooks (event-driven) or metadata but I think it makes sense to start with existing structure and generalize later when possible.

At any rate I don't think we are closed to any library, and remember that RS is about interop, at the end of the day it doesn't matter to have an extra 1.5Mb jar if it beautifully works when you adapt in Akka / Rx because we all have adopted RS ! Spring even does that automatically for you and I'm pretty sure we will see Jakarta doing the same in a few years.

**Comment by nebhale** [comment]
> It would probably be overkill to put r2dbc-client APIs behind RS-impl agnostic interfaces, so I was wondering if the R2DBC folks would be open to the idea of alternative r2dbc client libraries that used different RS impls, such as `r2dbc-client-rxjava` or `r2dbc-client-akka` under the r2dbc org?

The `r2dbc-client` is intended to be one option out of many at the client level (remember that no human is supposed to use the SPI directly).  Given that the API there is RS-compatible and it’s already the least-used client implementation (Spring Data R2DBC is much more popular) I don’t have any big rush to introduce equivalent, but different implementation clients as part of R2DBC.  If you want to create such a thing though, don’t let me stop you!  Go ahead and create it in your own org announce it on the mailing list and promote it out in the world; we’ll be happy to promote it as part of talks on R2DBC as well.  What is much more interesting to me would be including alternative client _types_ (e.g. Spring Data-style repositories, JPA-style ORM, etc.) and the implementation library choice wouldn’t be a gating factor for those.

**Comment by aguibert** [comment]
> The r2dbc-client is intended to be one option out of many at the client level (remember that no human is supposed to use the SPI directly).

Good point.  I had assumed that the r2dbc-client was still used by upstack libs such as Spring Data. For example:
4) User application
3) Spring Data R2DBC
2) R2DBC Client
1) R2DBC SPI w/ impl
But I suppose layer (2) isn't really necessary and layer (3) can just use layer (1) directly.

>  I don’t have any big rush to introduce equivalent, but different implementation clients as part of R2DBC. If you want to create such a thing though, don’t let me stop you!

I wasn't suggesting that you go re-implement a client lib for me (that would be a tall order!).  Rather, I have been thinking of ways to integrate R2DBC with other technologies I work with. Hopefully more to come on this!

**Comment by nebhale** [comment]
Exactly right.  The SPI is supposed to be designed in such a way that many clients, with different implementation technologies, data access metaphors, etc. can use the same set of drivers.

Looking forward to what you come up with!
