### ISSUE TITLE
R2DBC API: Provide Statement.bindNull(…) accepting integer index

### ISSUE THREAD

**Issue by mp911de** [r2dbc/r2dbc-client#4]
The `Statement` API should accept `null` bindings using an integer index.

**Comment by nebhale** [comment]
In this case, I agreed with something the ADBC team says, and that's that rather than putting a JDBC/ADBC abstraction around parameter binding, just use the existing parameter binding from the databases themselves, to be consistent with databases across languages rather than consistent with Java across databases.

So, PostgreSQL only supports `$#` binding parameters.  We could write a mapping from something else onto that, but I'd actually made the decision to support only that scheme since that's what PostgreSQL supports natively.

Let's definitely discuss this a bit.

**Comment by nebhale** [comment]
This issue was moved to r2dbc/r2dbc-spi#5
